# /!\ /!\ /!\ DO NOT EDIT THIS FILE /!\ /!\ /!\ 
# Only constraints.tcl and input_files.tcl should be modified.

#############################################################################
# This file is part of uvgKvazaarHW.
#
# Copyright (c) 2025, Tampere University, ITU/ISO/IEC, project contributors
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or
#   other materials provided with the distribution.
# 
# * Neither the name of the Tampere University or ITU/ISO/IEC nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# INCLUDING NEGLIGENCE OR OTHERWISE ARISING IN ANY WAY OUT OF THE USE OF THIS
#############################################################################

# Establish the location of this script and use it to reference all
# other files in this example
set sfd [file dirname [file normalize [info script]]]

# Include the lists of input files
set input_filename "input_files.tcl"
source $sfd/$input_filename
set constraint_filename "constraints.tcl"
source $sfd/$constraint_filename

# Reset the options to the factory defaults
options defaults
project new

# Set working directory
# file delete -force $sfd/working_dir
file mkdir $sfd/working_dir
set_working_dir $sfd/working_dir

flow package require /SCVerify

# Set research path for common header files
# $search_paths is defined in input_files.tcl
foreach search_path $search_paths {
    options set Input/SearchPath [file join $sfd $search_path] -append
}

# $header_files $src_files $testbench_files are defined in input_files.tcl
foreach header $header_files {
    solution file add [file join $sfd $header] -type C++ -exclude true
}

foreach src $src_files {
    solution file add [file join $sfd $src] -type C++
}

foreach tb $testbench_files {
    solution file add [file join $sfd $tb] -type C++ -exclude true
}

project save

# This procedure is defined in the constraints.tcl file
set_analyse_directives
go analyze

# Set the list of libraries to be used
solution library remove *
solution library add mgc_Altera-Arria-10-2_beh -- -rtlsyntool Quartus -manufacturer Altera -family {Arria 10} -speed 2 -part 10AX115N2F40I2SG
solution library add Altera_ROMS
solution library add Altera_DIST
solution library add Altera_FIFO
solution library add Altera_M20K
solution library add Altera_MLAB
go libraries

# Run testbench on original design
flow run /SCVerify/launch_make ./scverify/Verify_orig_cxx_osci.mk {} SIMTOOL=osci sim

# This procedure is defined in the constraints.tcl file
set_assembly_directives
go assembly

# This procedure is defined in the constraints.tcl file
set_extract_directives
go extract

puts "HDL file has been generated."
